feat: create new tmux session with the current dir name

diff --git a/defaults/bash/aliases b/defaults/bash/aliases
--- a/defaults/bash/aliases
+++ b/defaults/bash/aliases
@@ -50,17 +50,24 @@ new_project() {
     local project_name="$1"
     local project_type="$2"
     local dir_prefix="$HOME/coding"
+    local project_path
 
     if [ "$project_type" = "work" ]; then
         dir_prefix="$HOME/work"
     fi
 
-    local project_path="${dir_prefix}/${project_name}"
-    echo "Creating directory: \"$project_path\""
-    mkdir -p "$project_path"
-    if [ $? -ne 0 ]; then
-        echo "Error: Failed to create directory \"$project_path\"."
-        return 1
+    if [ "$project_name" = "." ]; then
+        # Use current directory name as session name and path
+        project_path="$(pwd)"
+        project_name="$(basename "$project_path")"
+    else
+        project_path="${dir_prefix}/${project_name}"
+        echo "Creating directory: \"$project_path\""
+        mkdir -p "$project_path"
+        if [ $? -ne 0 ]; then
+            echo "Error: Failed to create directory \"$project_path\"."
+            return 1
+        fi
     fi
 
     # Prevents errors if accidentally run it twice
